import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import { Navbar } from "../components/layout/Navbar";
import "./globals.css";
import Footer from "@/components/layout/Footer";

const lexendFont = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
  fallback: ["Lexend Deca", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexendFont.variable} font-lexend antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
